### ISSUE TITLE
During Offline Embedding. RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by permia** [ml4bio/Dense-Homolog-Retrieval#23]
Hi, I run the following commond to build the database for small file (all_full.tsv) about 3.17 MB :
```
SEQDB_PATH=/home/fastMSA/all_full.tsv
MODEL_PATH=/home/Dense-Homolog-Retrieval/Dense-Homolog-Retrieval-main/
OUTPUT_PATH=/home/fastMSA/output
python3 do_embedding.py trainer.ur90_path=$SEQDB_PATH model.ckpt_path=$MODEL_PATH hydra.run.dir=$OUTPUT_PATH
```

RuntimeError: CUDA out of memory. Tried to allocate 9.59 GiB (GPU 0; 15.72 GiB total capacity; 11.27 GiB already allocated; 2.76 GiB free; 11.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Predicting:   0%|

**Comment by heathcliff233** [comment]
Sorry for the late reply. Please try to reduce the batch_size in configuration to fit your memory. The embedding is done batch by batch instead of taking all sequences at once.

**Comment by permia** [comment]
> Sorry for the late reply. Please try to reduce the batch_size in configuration to fit your memory. The embedding is done batch by batch instead of taking all sequences at once.

Thanks a lot for reply.

After reducing the batch_size in the two configuration file (scale_conf.yaml and pred_conf.yaml), it worked well.
